services:
  zannime:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: zannime
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production

  wajik-anime-api:
    build:
      context: wajik-anime-api
      dockerfile: Dockerfile
    container_name: wajik-anime-api
    restart: unless-stopped
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production